export const SET_USERS = 'SET_USERS';
export const SET_POSTS = 'SET_POSTS';
export const SET_COMMENTS = 'SET_COMMENTS';
export const SET_USER_ACTIVITY_DATA = 'SET_USER_ACTIVITY_DATA';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETE_COMMENT_REPLY = 'DELETE_COMMENT_REPLY';
