export const SET_MODAL = 'SET_MODAL';
export const SET_LOADER = 'SET_LOADER';
export const SET_POST = 'SET_POST';
export const SET_SIGNIN_WELCOME = 'SET_SIGNIN_WELCOME';
export const SET_SIGNUP_WELCOME = 'SET_SIGNUP_WELCOME';
export const SET_CONTACT_FORM = 'SET_CONTACT_FORM';
